name: Deploy to Koyeb

on:
  push:
    branches:
      - master  # Change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust the Python version as needed

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Deploy to Koyeb
      env:
        KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
      run: |
        curl -s -H "Authorization: Bearer $KOYEB_API_TOKEN" https://app.koyeb.com/v1/apps -o apps.json
        APP_ID=$(jq -r '.apps[] | select(.name=="<YOUR_APP_NAME>") | .id' apps.json)

        if [ -z "$APP_ID" ]; then
          echo "App not found!"
          exit 1
        fi

        curl -X POST \
          -H "Authorization: Bearer $KOYEB_API_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"spec":{"name":"<YOUR_APP_NAME>","deployment":{"build_command":"pip install -r requirements.txt","run_command":"gunicorn app:app"}}}' \
          https://app.koyeb.com/v1/apps/$APP_ID/services
